export const projects = [
  { name: 'HYPERSHAPE', field: 'Geometry', title: 'An axis you cannot point to.', description: 'Turn a shape through the fourth dimension. Watch the impossible become a little more familiar as its hidden axis passes through color.', detail: '38 shape families · six planes of rotation', color: '#efb85e', symbol: '01', label: 'The fourth dimension' },
  { name: 'LUMA', field: 'Perception', title: 'Color is a construction.', description: 'Six experiments about the space between a pixel and a perception. Walk through color, bend a gradient, and find the edges of what your eyes can see.', detail: 'Six experiments on color and the eye', color: '#ec939f', symbol: '02', label: 'The color chamber' },
  { name: 'LUMASHAPE', field: 'Color × geometry', title: 'The primary you are missing.', description: 'A bird has a fourth kind of cone. Explore its four-dimensional receptor space, then collapse it into the smaller world a human eye knows.', detail: '4,096 receptor states · one invisible axis', color: '#b8a0fa', symbol: '03', label: 'The ultraviolet cabinet' },
  { name: 'APSIS', field: 'Relativity', title: 'Even light takes the long way.', description: 'Send light past a black hole. Its shadow, photon ring, and distorted disk emerge from paths bent by the geometry of spacetime.', detail: 'Schwarzschild geodesics · a live measurement log', color: '#edac78', symbol: '04', label: 'The gravity well' },
  { name: 'GOLDILOCKS', field: 'Astrobiology', title: 'A small window for water.', description: 'Build a star and give it a world. Adjust the orbit and atmosphere, follow a transit, and ask where liquid water could survive.', detail: 'Stars, transits, worlds, and the conditions for life', color: '#7cdbc0', symbol: '05', label: 'The habitable world' },
  { name: 'QUASI', field: 'Aperiodic matter', title: 'Order without repetition.', description: 'Cut a lattice from a higher dimension. A Fibonacci chain becomes a Penrose tiling. Its diffraction reveals a symmetry a repeating crystal cannot have.', detail: 'Five dimensions · tenfold diffraction', color: '#e8c472', symbol: '06', label: 'The forbidden crystal' },
  { name: 'DIFFUSE', field: 'Emergence', title: 'A thousand accidents. One law.', description: 'Random walkers find a diffusion law. A chemical gradient gives cells an address. Two reacting chemicals discover spots, stripes, and living patterns.', detail: 'Random walks · morphogens · Turing patterns', color: '#79a9eb', symbol: '07', label: 'The pattern garden' },
  { name: 'META', field: 'Metamaterials', title: 'A material made of its shape.', description: 'Pull a lattice and watch it grow wider. Change its cells to change its stiffness, then send a wave through and find which frequencies cannot pass.', detail: 'Negative Poisson ratios · stiffness · phononic gaps', color: '#7ed3df', symbol: '08', label: 'The mechanical specimen' },
  { name: 'VALENCE', field: 'Quantum chemistry', title: 'The electron is a wave.', description: 'See hydrogen orbitals drawn from their wavefunctions. Mix states, let molecular shapes settle, and take chemistry through one more dimension.', detail: 'Hydrogen orbitals · molecular geometry · 4D chemistry', color: '#e5d48e', symbol: '09', label: 'The wavefunction' },
].map(project => ({ ...project, url: `https://mowke.github.io/${project.name}/` }));

export function exhibitPosition(index) {
  const angle = Math.PI * 0.76 + index * Math.PI * 2 / projects.length;
  return { x: Math.sin(angle) * 12.8, z: Math.cos(angle) * 12.8, angle };
}
